### ISSUE TITLE
Secrets configuration

### ISSUE THREAD

**Issue by xadcoh** [microsoft/AmbariBasedHadoopExporter#13]
Hi

I'm trying to run container with next configuration:

```
{
  "LogLevel": "Debug",
  "Secrets": {
    "Path": "/app/test",
    "Mapping": {
      "ambariConnectionUsername": "AmbariConnection--Username", 
      "ambariConnectionPassword": "AmbariConnection--Password"
    }
  },
  "BaseExporterConfiguration": {
    "ClusterName": "cli-cluster",
    "AmbariServerUri": "http://10.0.0.5:8080/api/v1/clusters",
    "DefaultLabels": {
      "TestLabelName": "TestLabelValue"
    }
  },
  "PrometheusExporterConfiguration": {
    "Port": 8086
  },
  "LivenessConfiguration": {
    "SamplingPeriodInMinutes" : 1
  }
}
```

I'm using next command:

```
docker run -it --rm --network=host -v $PWD/SecretFolder:/app/test -v $PWD/appsettings.json:/app/appsettings.json ambari-exporter:latest
```

SecretFolder have 2 files:

```
ambariConnectionPassword 
ambariConnectionUsername
```

I can successfully access ambari via command:

```
curl -u admin:password http://10.0.0.5:8080/api/v1/clusters/
```

But app is crashing with an error:

```
Fetching secrets from folder /app/test.
SecretConfigurationExtension::AddSecretProvider - resolved 2 secrets.
SecretConfigurationExtension::AddSecretProvider - mapped the following: 'ambariConnectionPassword' -> 'AmbariConnection:Password'.
SecretConfigurationExtension::AddSecretProvider - mapped the following: 'ambariConnectionUsername' -> 'AmbariConnection:Username'.
{"LogTimestamp":"2020-01-15T16:03:08.8934489Z","Level":"Debug","LevelId":1,"Message":"Hosting starting","CustomFields":{"EventId":{"Id":1},"SourceContext":"Microsoft.Extensions.Hosting.Internal.Host"}}
{"LogTimestamp":"2020-01-15T16:03:09.1784481Z","Level":"Information","LevelId":2,"Message":"Starting Prometheus MetricServer at 01/15/2020 16:03:09.","CustomFields":{"SourceContext":"App.Services.Hosted.PrometheusExporterHostedService"}}
{"LogTimestamp":"2020-01-15T16:03:09.2078564Z","Level":"Information","LevelId":2,"Message":"Starting the service - initializing and starting the timer.","CustomFields":{"SourceContext":"App.Services.Hosted.LivenessHostedService"}}
Application started. Press Ctrl+C to shut down.
Hosting environment: Production
Content root path: /app/
{"LogTimestamp":"2020-01-15T16:03:09.2100355Z","Level":"Debug","LevelId":1,"Message":"Hosting started","CustomFields":{"EventId":{"Id":2},"SourceContext":"Microsoft.Extensions.Hosting.Internal.Host"}}
{"LogTimestamp":"2020-01-15T16:03:09.2133152Z","Level":"Information","LevelId":2,"Message":"Running HealthCheck.","CustomFields":{"SourceContext":"App.Services.Hosted.LivenessHostedService"}}
{"LogTimestamp":"2020-01-15T16:03:09.3101379Z","Level":"Error","LevelId":4,"Message":"Failed to get response from Ambari: http://10.0.0.5:8080/api/v1/clusters.","Exception":{"Type":"System.Net.Http.HttpRequestException","Message":"Status code: Forbidden isnt Ok.","StackTrace":"   at Infrastructure.Providers.Concrete.AmbariApiContentProvider.GetResponseContentAsync(String uriEndpoint) in /app/src/Infrastructure/Providers/Concrete/AmbariApiContentProvider.cs:line 58"},"CustomFields":{"SourceContext":"Infrastructure.Providers.Concrete.AmbariApiContentProvider"}}
{"LogTimestamp":"2020-01-15T16:03:09.3340873Z","Level":"Error","LevelId":4,"Message":"HealthCheck failed.","Exception":{"Type":"System.Net.Http.HttpRequestException","Message":"Status code: Forbidden isnt Ok.","StackTrace":"   at Infrastructure.Providers.Concrete.AmbariApiContentProvider.GetResponseContentAsync(String uriEndpoint) in /app/src/Infrastructure/Providers/Concrete/AmbariApiContentProvider.cs:line 58\n   at App.Services.Hosted.LivenessHostedService.HealthCheck(Object state) in /app/src/App/Services/Hosted/LivenessHostedService.cs:line 73"},"CustomFields":{"SourceContext":"App.Services.Hosted.LivenessHostedService"}}

Unhandled Exception: System.Net.Http.HttpRequestException: Status code: Forbidden isnt Ok.
   at App.Services.Hosted.LivenessHostedService.HealthCheck(Object state) in /app/src/App/Services/Hosted/LivenessHostedService.cs:line 82
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

It looks like I misconfigured login and password

**Comment by xadcoh** [comment]
I will answer myself. Creds are good, it's update in .Net Core I suppose: https://github.com/dotnet/corefx/issues/30349

So I updated `AmbariApiContentProvider.cs`:

```
        public AmbariApiContentProvider(IOptions<AmbariClientConfiguration> configuration, ILogger<AmbariApiContentProvider> logger)
        {
            _configuration = configuration.Value;
            _logger = logger;
            var _authHeader = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes(string.Format("{0}:{1}", _configuration.Username, _configuration.Password))));
            Console.WriteLine($"{_authHeader}");
            _httpClient = new HttpClient(new HttpClientHandler
            {
                Credentials = new NetworkCredential(_configuration.Username, _configuration.Password),
                AllowAutoRedirect = false,
                PreAuthenticate = true,
                MaxConnectionsPerServer = 256,
            });

            _httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes(string.Format("{0}:{1}", _configuration.Username, _configuration.Password))));
        }
```

**Comment by SolomonTomer** [comment]
Hey @xadcoh ,
Thank you for your feedback and sorry for the very late response.

I will look into that and communicate back.
